# fly.toml app configuration file generated for auditkit-api on 2026-03-09T18:55:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'auditkit-api'
primary_region = 'iad'

[build]
  dockerfile = 'docker/Dockerfile'

[env]
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'
  PORT = '3001'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
